language: objective-c
os: osx
osx_image: xcode12.2
xcode_project: project-november.xcodeproj
xcode_scheme: project-november
xcode_sdk: iphonesimulator14.2

jobs:
  include:
    - stage: BuildAndArchive
      script: xcodebuild clean build -workspace $WORKSPACE_NAME -scheme $SCHEME -sdk $APP_SDK -destination $DESTINATION_DEVICE ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty